repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [ commit ]
        language: python
        types: [ python ]
        entry: venv/bin/black
      - id: isort
        name: isort
        stages: [ commit ]
        language: python
        types: [ python ]
        entry: venv/bin/isort
      - id: flake8
        name: flake8
        stages: [ commit ]
        language: python
        types: [ python ]
        entry: venv/bin/flake8
      - id: mypy
        name: mypy
        stages: [ commit ]
        language: python
        types: [ python ]
        entry: venv/bin/mypy
      - id: bandit
        name: bandit
        stages: [ commit ]
        language: python
        types: [ python ]
        entry: venv/bin/bandit
        args: [ "-c", "pyproject.toml" ]
